exclude: (^migrations/+.|^tests/+.|^venv/+.|^.venv/+.|^env/+.|^.tox/+.|^build/+.|docs)
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
#  - repo: https://github.com/myint/autoflake
#    rev: v2.3.1
#    hooks:
#      - id: autoflake
#        exclude: .*/__init__.py
#        args: [--in-place, --remove-all-unused-imports, --expand-star-imports]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.1
    hooks:
      - id: pydoclint
        args: [--style=google, --check-return-types=False]
  - repo: https://github.com/facebook/usort
    rev: v1.0.8
    hooks:
      - id: usort
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.9.0
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests, types-pytz, types-aiofiles]
#  - repo: https://github.com/pycqa/pylint
#    rev: v3.1.0
#    hooks:
#      - id: pylint
#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.358
#    hooks:
#      - id: pyright
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, -lll]
