default_language_version:
  python: python3
repos:
#  - repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: v0.5.5
#    hooks:
#      - id: ruff
#        args: [--select, ALL]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: check-json
        args: [--select, ALL]
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.5.6
    hooks:
      - id: pydoclint
        args: [--style=google, --check-return-types=False]
  - repo: https://github.com/facebook/usort
    rev: v1.0.8
    hooks:
      - id: usort
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
#  - repo: https://github.com/psf/black
#    rev: 24.4.2
#    hooks:
#      - id: black
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.11.1
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests, types-pytz, types-aiofiles]
#  - repo: https://github.com/pycqa/pylint
#    rev: v3.2.6
#    hooks:
#      - id: pylint
#        args: [--style=google, --check-return-types=False]
#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.358
#    hooks:
#      - id: pyright
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-r, -lll]
