"""add constraint to mood table

Revision ID: 80b41d8fd30d
Revises: b836e051c5fd
Create Date: 2024-09-04 21:35:27.260316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b41d8fd30d'
down_revision: Union[str, None] = 'b836e051c5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_mood_user_emotion_date",
        "mood",
        ["user_id", "emotion", "date"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_mood_user_emotion_date",
        "mood",
        type_="unique"
    )
    # ### end Alembic commands ###
