"""add mood table

Revision ID: b836e051c5fd
Revises: d7931796808f
Create Date: 2024-09-01 13:05:14.506985

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b836e051c5fd"
down_revision: Union[str, None] = "d7931796808f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mood",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column(
            "emotion",
            sa.Enum(
                "HAPPINESS", "SADNESS", "FEAR", "ANGER", name="emotion_enum"
            ).with_variant(
                postgresql.ENUM(
                    "HAPPINESS",
                    "SADNESS",
                    "FEAR",
                    "ANGER",
                    name="emotion_enum",
                    create_type=True,
                ),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column("percentage", sa.Double(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mood")
    # ### end Alembic commands ###
